name: 📦 Build/Install Issue
description: Use this template to report build/install issue
labels: [build, install]
body:
  - type: markdown
    attributes:
      value: Please make sure that this is a build/installation issue.
  - type: input
    attributes:
      label: OS Platform and Distribution
      description: Please describe your operating system
      placeholder: e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4
    validations:
      required: true
  - type: input
    id: programminglang
    attributes:
      label: Programming Language and version
      description: Please describe which Python version you are using
      placeholder: e.g. C++ 14, Python 3.6, Java
    validations:
      required: true
  - type: input
    id: virtualenv
    attributes:
      label: Installed using virtualenv? pip? Conda? pipenv?(if python)
      description: Please specify which package manager are you using
      placeholder: e.g. Conda
    validations:
      required: false
  - type: input
    attributes:
      label: Docker version (if applicable)
      description: Please specify which docker version are you using
      placeholder: e.g. 19.03.8
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the problem
      description: Provide the exact sequence of commands / steps that you executed before running into the problem.
      placeholder: Tell us what you see!
      value: "A bug happened!"
      render: shell
    validations:
      required: true
  - type: textarea
    id: code-to-reproduce
    attributes:
      label: Complete Logs
      description: Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached
      placeholder: Tell us what you see!
      value: "A bug happened!"	
      render: shell
    validations:
      required: true
